name: Docker Merge Digests into Manifest
description: Merge uploaded per-arch digests into a multi-arch manifest and inspect the image
inputs:
  image_repository:
    description: Docker image repository (e.g., user/repo)
    required: true
  tag:
    description: Tag to apply to the created manifest (e.g., latest-dev)
    required: true
  additional_tag:
    description: Additional tag to apply to the created manifest (optional)
    required: false
    default: ''
  dockerhub_username:
    description: Docker Hub username
    required: true
  dockerhub_token:
    description: Docker Hub token/password
    required: true

runs:
  using: composite
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image_repository }}
        tags: |
          type=raw,value=${{ inputs.tag }}
          type=raw,value=${{ inputs.additional_tag }},enable=${{ inputs.additional_tag != '' }}

    - name: Create manifest list and push
      shell: bash
      working-directory: ${{ runner.temp }}/digests
      run: |
        docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
          $(printf '${{ inputs.image_repository }}@sha256:%s ' *)

    - name: Inspect image
      shell: bash
      run: |
        docker buildx imagetools inspect ${{ inputs.image_repository }}:${{ steps.meta.outputs.version }}
