language: php

php:
  - "7.2"
  - "7.3"

services:
  - redis-server

addons:
  mariadb: "10.1"
  chrome: stable

cache:
  directories:
    - site/vendor
    - $HOME/.composer/cache

before_install: cd site

install:
  - mysql -e 'CREATE DATABASE training;'
  - cp .env.testing .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - npm install
  - npm run prod
  - php artisan key:generate
  - php artisan migrate

before_script:
  - php artisan dusk:chrome-driver
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - php artisan dusk
