language: php
dist: bionic
php:
- '7.3'
services:
- redis-server
addons:
  chrome: stable
  mariadb: '10.3'
cache:
  directories:
  - site/vendor
  - "$HOME/.composer/cache"
before_install: cd site
install:
- mysql -e 'CREATE DATABASE training_test;'
- mysql -e "SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION';"
- cp .env.testing .env
- travis_retry composer install --no-interaction --prefer-dist --no-suggest
- php artisan key:generate
- php artisan migrate
before_script:
- php artisan dusk:chrome-driver
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
- php artisan serve &
script:
- php artisan dusk
- "./vendor/bin/phpunit"
notifications:
  slack:
    secure: ZWNnL53cjBtT4R2o/5YFhGINH5mGZ373a7OoKzhME6Jop412nBVB9wglH8q+WXBFjdjoA1uC6m0L4AQ/qwgWh7db8NC9NxP0yypYOoNDgz4Fct3nzVBLDjYar3yJXNg4iKz9G/TIysJCeys/Mo6boW5xtMhmZyUWNjNW4Y3sW5WYttScTIxczuTdwGzikU2EyjExekptKR76Xuuf0R4VKa5kD3+i0ySTFVWXss/WgEMP2aU8YJ7wxw9efwOO5k4tWqe5ertWqpOChRvC+JdCQCIqJ/rebEnNfeV/8cI5PMMDG1e1olKMULGecH7SaATSYpwnAuiJ50WgVp8+Ir36OSzT2VP3n4SrEbxFQfROvKGJiLm3mVVml+oJ8l6B715grKs9BiE7emV4GK04f+biCfDgXPam3RwlYWFQea79thUpKYFghnXrVyS/BMvZVO3DtX5FnSnULYBB3biGOgpZTQJZjTtpUQpOfbgpS/H52FzSw+y5XcDYiPpBI0bSOAwHISX95bhpdlV29cYu1ScKZENErzQcGDjB6Gff3xPhr1Wm9bXwgJr9z5x4WwCKbcJeyFd3BkisjbBzAuOul10xtaZkCJmbDLUfi22exoiFuYNFIqSBj7SZbn1rQL0Q1/3pRcYOaqjz3OXXvZiFaHQ9hUYLhQiEqDxK1flkGuIRp+I=
