networks:
  training-net:
    driver: bridge

name: training

services:
  train-app:
    ports:
      - "127.0.0.1:8686:80"
    depends_on:
      train-mysql:
        condition: service_healthy
    networks:
      - training-net
    container_name: train-app
  train-mysql:
    image: mariadb:10.6
    env_file:
      - ./docker/.env
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/config/my.cnf:/etc/mysql/my.cnf
    ports:
      - "127.0.0.1:3302:3306"
    healthcheck:
      # The container is not considered healthy until the MYSQL_DATABASE database is available
      test: [ "CMD-SHELL", "mysql $${MYSQL_DATABASE} -u$${MYSQL_USER} -p$${MYSQL_PASSWORD} -e 'SELECT 1;'  || exit 1" ]
      interval: 2s
      retries: 5
    networks:
      - training-net
    container_name: train-mysql

volumes:
  mysql-data:
