version: '2.4'

networks:
  training-net:
    driver: bridge

services:
  train-app:
    image: unillett/training:latest
    env_file:
      - ./dev/.env
    volumes:
      - ./site:/var/www
    working_dir: /var/www
    expose:
      - "9000"
    networks:
      - training-net
    container_name: train-app
  train-web:
    image: nginx:1.17
    env_file:
      - ./dev/.env
    working_dir: /var/www
    volumes:
      - ./dev/config/vhost.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - train-app
    ports:
      - "8686:80"
    networks:
      - training-net
    container_name: train-web
  train-mariadb:
    image: mariadb:10.4
    env_file:
      - ./dev/.env
    volumes:
      - ./dev/dbdata:/var/lib/mysql
      - ./dev/config/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3302:3306"
    networks:
      - training-net
    container_name: train-mysql
  train-myadmin:
    image: phpmyadmin/phpmyadmin:latest
    env_file:
      - ./dev/.env
    ports:
      - "9999:80"
    networks:
      - training-net
    container_name: train-myadmin
  train-mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - training-net
    container_name: train-mailhog
