networks:
  training-net:
    driver: bridge

name: training

services:
  train-app:
    env_file:
      - ./docker/.env
    ports:
      - "127.0.0.1:8686:80"
    networks:
      - training-net
    container_name: train-app
  train-mysql:
    image: mariadb:10.6
    env_file:
      - ./docker/.env
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/config/my.cnf:/etc/mysql/my.cnf
    ports:
      - "127.0.0.1:3302:3306"
    networks:
      - training-net
    container_name: train-mysql

volumes:
  mysql-data:
