version: '2.4'

networks:
  training-net:
    driver: bridge

name: training

services:
  train-app:
    image: unillett/training:latest
    build:
      context: ./dev/config
      dockerfile: ./app.dockerfile
    env_file:
      - ./dev/.env
    volumes:
      - ./site:/var/www
      - ./dev/config/php.ini:/usr/local/etc/php/conf.d/uploads.ini
    working_dir: /var/www
    expose:
      - "9000"
    networks:
      - training-net
    container_name: train-app
  train-web:
    image: nginx:1.24
    env_file:
      - ./dev/.env
    working_dir: /var/www
    volumes:
      - ./dev/config/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./dev/config/nginx.conf:/etc/nginx/conf.d/nginx.conf
    volumes_from:
      - train-app
    ports:
      - "127.0.0.1:8686:80"
    networks:
      - training-net
    container_name: train-web
  train-mysql:
    image: mariadb:10.6
    env_file:
      - ./dev/.env
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dev/config/my.cnf:/etc/mysql/my.cnf
    ports:
      - "127.0.0.1:3302:3306"
    networks:
      - training-net
    container_name: train-mysql
  train-mysql-testing:
    image: mariadb:10.6
    env_file:
      - ./dev/.env
    volumes:
      - dusk-data:/var/lib/mysql
      - ./dev/config/my-testing.cnf:/etc/mysql/my.cnf
    expose:
      - "3307"
    networks:
      - training-net
    container_name: train-mysql-testing
  train-myadmin:
    image: phpmyadmin/phpmyadmin:latest
    env_file:
      - ./dev/.env
    ports:
      - "127.0.0.1:9999:80"
    networks:
      - training-net
    container_name: train-myadmin
  train-mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "127.0.0.1:1025:1025"
      - "127.0.0.1:8025:8025"
    networks:
      - training-net
    container_name: train-mailhog
  train-selenium:
    image: selenium/standalone-chrome:latest
    shm_size: 2gb
    ports:
      - "127.0.0.1:4444:4444"
    networks:
      - training-net
    container_name: train-selenium

volumes:
  mysql-data:
  dusk-data:
