networks:
  training-net:
    driver: bridge

name: training

services:
  train-app:
    ports:
      - "127.0.0.1:8686:80"
    depends_on:
      train-mysql:
        condition: service_healthy
    networks:
      - training-net
    container_name: train-app
  train-mysql:
    image: mariadb:11.4
    env_file:
      - ./docker/.env
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/config/my.cnf:/etc/mysql/my.cnf
    ports:
      - "127.0.0.1:3309:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - training-net
    container_name: train-mysql

volumes:
  mysql-data:
