name: Docker Build and Upload Digest
description: Build a Docker image for a platform, push by digest, and upload the digest artifact
inputs:
  dockerfile:
    description: Path to the Dockerfile
    required: true
  target:
    description: Multi-stage target to build
    required: true
  platform:
    description: Target platform (e.g., linux/amd64)
    required: true
  image_repository:
    description: Docker image repository (e.g., user/repo)
    required: true
  name_prefix:
    description: Prefix for the digest artifact name (e.g., app or worker)
    required: true
  dockerhub_username:
    description: Docker Hub username
    required: true
  dockerhub_token:
    description: Docker Hub access token/password
    required: true
runs:
  using: composite
  steps:
    - name: Prepare
      shell: bash
      run: |
        platform='${{ inputs.platform }}'
        echo "PLATFORM_PAIR=${platform//\//-}" >> "$GITHUB_ENV"
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.image_repository }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}
    - name: Build and push by digest
      id: build
      uses: docker/build-push-action@v6
      with:
        context: ./
        file: ${{ inputs.dockerfile }}
        target: ${{ inputs.target }}
        platforms: ${{ inputs.platform }}
        labels: ${{ steps.meta.outputs.labels }}
        outputs: type=image,"name=${{ inputs.image_repository }}",push-by-digest=true,name-canonical=true,push=true
    - name: Export digest
      shell: bash
      run: |
        mkdir -p "$RUNNER_TEMP/digests"
        digest="${{ steps.build.outputs.digest }}"
        touch "$RUNNER_TEMP/digests/${digest#sha256:}"
    - name: Upload digest
      uses: actions/upload-artifact@v4
      with:
        name: digests-${{ inputs.name_prefix }}-${{ env.PLATFORM_PAIR }}
        path: ${{ runner.temp }}/digests/*
        if-no-files-found: error
        retention-days: 1
