name: ci
on: [push, pull_request]
env:
  MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
  CI: gha

jobs:
  test:
    name: PHP${{ matrix.php-versions }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php-versions: [ '8.1', '8.2' ]
        mariadb-version: [ '10.6' ]
        node-version: [ '18' ]

    services:
      mariadb:
        image: mariadb:${{ matrix.mariadb-version }}
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: training
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: PHP Setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Show PHP version
        run: php -v

      - name: Cache composer
        uses: actions/cache@v3
        with:
          path: ~/.cache/composer
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Mysql configuration
        run: mysql --protocol=tcp --user=root --execute='SET GLOBAL sql_mode = "";'

      - name: Add Backpack credentials
        working-directory: ./site
        run: composer config http-basic.backpackforlaravel.com ${{ secrets.BACKPACK_USERNAME }} ${{ secrets.BACKPACK_PASSWORD }}

      - name: Build app
        id: app-build
        working-directory: ./site
        run: ./setup.sh

      - name: Check PHP code style
        id: app-php-style
        working-directory: ./site
        run: ./vendor/bin/pint --test -v
        continue-on-error: true

      - name: Serve
        working-directory: ./site
        run: |
          php artisan dusk:chrome-driver --detect &
          ./vendor/laravel/dusk/bin/chromedriver-linux &
          php artisan serve &

      - name: Execute browser tests
        id: app-test-browser
        working-directory: ./site
        run: php artisan dusk

      - name: Execute unit/feature tests
        id: app-test-unit
        working-directory: ./site
        run: php artisan test

      - name: Expose failed tests
        working-directory: ./site
        run: php artisan email:failure
        if: failure()
