name: docker-prod
on:
  schedule:
    - cron: '0 1 * * 1'  # Every Monday at 1am UTC
  push:
    branches:
      - "master"
    tags:
      - "*"
permissions: read-all

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: linux/amd64
          - os: ubuntu-24.04-arm
            arch: linux/arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: master

      - name: Build image
        uses: unil-lettres/actions/docker-build@v1.0.0
        with:
          dockerfile: ./docker/app.dockerfile
          target: prod
          platform: ${{ matrix.arch }}
          image_repository: ${{ vars.DOCKERHUB_REPOSITORY }}
          name_prefix: app
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  merge:
    name: Merge
    runs-on: ubuntu-latest
    needs: [build]
    outputs:
      tag: ${{ steps.set-output-tag.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: master

      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Get tags
        id: get_tags
        uses: JinoArch/get-latest-tag@latest

      - name: Compute tag (push)
        if: github.event_name == 'push'
        id: push-tag
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/master" ]]; then
            echo "publish_tag=latest" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" =~ ^refs/tags/.*$ ]]; then
            echo "publish_tag=${{ steps.get_tags.outputs.latestTag }}" >> $GITHUB_OUTPUT
          else
            echo "publish_tag=latest" >> $GITHUB_OUTPUT
          fi

      - name: Merge digests and tag (push)
        if: github.event_name == 'push'
        uses: unil-lettres/actions/docker-merge@v1.0.0
        with:
          image_repository: ${{ vars.DOCKERHUB_REPOSITORY }}
          tag: ${{ steps.push-tag.outputs.publish_tag }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set additional tag (cron)
        if: github.event_name == 'schedule'
        id: cron-tag
        run: |
          LATEST_TAG=${{ steps.get_tags.outputs.latestTag }}
          SHORT_SHA=$(echo $(git rev-parse HEAD) | cut -c1-7)
          TIMESTAMP=$(date -u +"%Y%m%d%H%M%S")
          ADDITIONAL_TAG="${LATEST_TAG}-${SHORT_SHA}-${TIMESTAMP}"
          echo "additional_tag=$ADDITIONAL_TAG" >> $GITHUB_OUTPUT

      - name: Merge digests and tag (cron)
        if: github.event_name == 'schedule'
        uses: unil-lettres/actions/docker-merge@v1.0.0
        with:
          image_repository: ${{ vars.DOCKERHUB_REPOSITORY }}
          tag: latest
          additional_tag: ${{ steps.cron-tag.outputs.additional_tag }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set output tag
        id: set-output-tag
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "tag=${{ steps.push-tag.outputs.publish_tag }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ steps.cron-tag.outputs.additional_tag }}" >> $GITHUB_OUTPUT
          fi

  commit:
    name: Commit Image Tag
    if: github.event_name == 'schedule' || github.ref_type == 'tag'
    runs-on: ubuntu-latest
    needs: [merge]

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: master

      - name: Update image
        uses: unil-lettres/actions/commit-version@v1.0.0
        with:
          file_path: training/values-prod.yaml
          version: ${{ needs.merge.outputs.tag }}
          version_keys: "app_image_tag"
          token: ${{ secrets.PAT_TOKEN }}
          repository: unil-lettres/k8s
          branch: main

  update-description:
    name: Update Description
    runs-on: ubuntu-latest
    needs: [merge]

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: master

      - name: Update description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ vars.DOCKERHUB_REPOSITORY }}
