name: docker-prod
on:
  schedule:
    - cron: '0 1 * * 1'  # Every Monday at 1am
  push:
    branches:
      - "master"
    tags:
      - "*"
permissions: read-all

jobs:
  build:
    name: Build app (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { arch: linux/amd64, os: ubuntu-latest }
          - { arch: linux/arm64, os: ubuntu-24.04-arm }

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: master

      - name: Build image
        uses: unil-lettres/actions/docker-build@v2.2.0
        with:
          dockerfile: ./docker/app.dockerfile
          target: prod
          platform: ${{ matrix.arch }}
          image_repository: ${{ vars.DOCKERHUB_REPOSITORY }}
          name_prefix: app
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  merge:
    name: Merge
    runs-on: ubuntu-latest
    needs: [build]
    outputs:
      tag: ${{ steps.merge.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: master

      - name: Merge service
        id: merge
        uses: unil-lettres/actions/docker-merge-prod@v2.2.0
        with:
          image_repository: ${{ vars.DOCKERHUB_REPOSITORY }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  commit:
    name: Commit Image Tag
    if: github.event_name == 'schedule' || github.ref_type == 'tag'
    runs-on: ubuntu-latest
    needs: [merge]

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: master

      - name: Update image
        uses: unil-lettres/actions/commit-version@v2.2.0
        with:
          file_path: training/values-prod.yaml
          versions: "${{ needs.merge.outputs.tag }}"
          version_keys: "app_image_tag"
          token: ${{ secrets.PAT_TOKEN }}
          repository: unil-lettres/k8s
          branch: main

  update-description:
    name: Update Description
    runs-on: ubuntu-latest
    needs: [merge]

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: master

      - name: Update description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ vars.DOCKERHUB_REPOSITORY }}
